-- Active: 1759537359752@@177.131.33.17@1521@XE@262413540
-- 1.
SELECT 
  Clientes.CLI_NOME,
  SUM(Parcelas.PARC_VALOR) AS TOTAL
FROM MAT_CLIENTES Clientes
INNER JOIN MAT_VENDAS Vendas ON Vendas.CLI_COD = Clientes.CLI_COD
INNER JOIN MAT_PARCELA_RECEBER Parcelas ON Parcelas.VEN_COD = Vendas.VEN_COD
WHERE Parcelas.PARC_DTVENCTO BETWEEN CURRENT_DATE AND CURRENT_DATE + 60
GROUP BY Clientes.CLI_NOME

-- Visualizar parcelas a receber de todos os clientes do São Paulo
SELECT * FROM MAT_PARCELA_RECEBER Parcelas
WHERE Parcelas.VEN_COD IN (
  SELECT 
    Vendas.VEN_COD 
  FROM MAT_VENDAS Vendas
  INNER JOIN MAT_CLIENTES Clientes ON Clientes.CLI_COD = Vendas.CLI_COD
  INNER JOIN MAT_CIDADES Cidades ON Cidades.CID_COD = Clientes.CID_COD_RESID
  WHERE Cidades.EST_UF = 'SP'
)

-- 2.
UPDATE MAT_PARCELA_RECEBER Parcelas 
SET Parcelas.PARC_DTVENCTO = Parcelas.PARC_DTVENCTO - 40
WHERE Parcelas.VEN_COD IN (
  SELECT 
    Vendas.VEN_COD 
  FROM MAT_VENDAS Vendas
  INNER JOIN MAT_CLIENTES Clientes ON Clientes.CLI_COD = Vendas.CLI_COD
  INNER JOIN MAT_CIDADES Cidades ON Cidades.CID_COD = Clientes.CID_COD_RESID
  WHERE Cidades.EST_UF = 'SP'
)

-- 3
SELECT
  Cidades.EST_UF,
  SUM(Parcelas.PARC_VALOR) AS Total
FROM MAT_PARCELA_RECEBER Parcelas
INNER JOIN MAT_VENDAS Vendas ON Vendas.VEN_COD = Parcelas.VEN_COD
INNER JOIN MAT_CLIENTES Clientes ON Clientes.CLI_COD = Vendas.CLI_COD
INNER JOIN MAT_CIDADES Cidades ON Cidades.CID_COD = Clientes.CID_COD_RESID
WHERE Parcelas.PARC_DTVENCTO < CURRENT_DATE AND Parcelas.PARC_DTPAGTO IS NULL
GROUP BY Cidades.EST_UF

-- 4
UPDATE MAT_CLIENTES SET CID_COD_RESID = NULL WHERE CLI_COD IN (2,4,10,15,21);
COMMIT;

-- 5
SELECT 
  Clientes.CLI_NOME,
  Cidades.CID_NOME
FROM MAT_CLIENTES Clientes
LEFT JOIN MAT_CIDADES Cidades ON Cidades.CID_COD = Clientes.CID_COD_RESID

-- 6: Não sei

-- 7
SELECT,
  Cidades.CID_NOME,
  COUNT(*) AS TOTAL_CLIENTES_CADASTRADOS
FROM MAT_CIDADES Cidades
JOIN MAT_CLIENTES Clientes ON Clientes.CID_COD_RESID = Cidades.CID_COD
GROUP BY Cidades.CID_NOME

-- 8
SELECT
  COUNT(*) AS TOTAL
FROM MAT_CLIENTES Clientes
JOIN MAT_CIDADES Cidades ON Cidades.CID_COD = Clientes.CID_COD_RESID
JOIN MAT_ESTADOS Estados ON Estados.EST_UF = Cidades.EST_UF
WHERE Estados.EST_UF = 'SP'

-- 9
SELECT
  Clientes.CLI_NOME,
  SUM(Vendas.VEN_TOTAL) AS TOTAL_VENDAS_POR_CLIENTE
FROM MAT_VENDAS Vendas
JOIN MAT_CLIENTES Clientes ON Clientes.CLI_COD = Vendas.CLI_COD
GROUP BY Clientes.CLI_NOME
UNION
SELECT
  Cidades.CID_NOME,
  SUM(Vendas.VEN_TOTAL) AS TOTAL_VENDAS_POR_CIDADE
FROM MAT_VENDAS Vendas
JOIN MAT_CLIENTES Clientes ON Clientes.CLI_COD = Vendas.CLI_COD
JOIN MAT_CIDADES Cidades ON Cidades.CID_COD = Clientes.CID_COD_RESID
GROUP BY Cidades.CID_NOME

-- 10
SELECT
  COUNT(*) AS TOTAL_VENDAS_POR_CLIENTE
FROM MAT_CLIENTES Clientes
JOIN MAT_VENDAS Vendas ON Vendas.CLI_COD = Clientes.CLI_COD
JOIN MAT_CIDADES Cidades ON Cidades.CID_COD = Clientes.CID_COD_RESID
WHERE Cidades.EST_UF = 'SP'